language: cpp
os: linux
dist: bionic

jobs:
  include:
    - name: unittests - GCC without optimisations
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O0"
      script:
        - make unittests || (cat unittests/test-suite.log && false)
    - name: unittests - GCC with optimisations on level 2
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O2"
      script:
        - make unittests || (cat unittests/test-suite.log && false)
    - name: unittests - GCC with optimisations on level 3
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O3"
      script:
        - make unittests || (cat unittests/test-suite.log && false)
    - name: unittests - GCC without optimisations and AddressSanitizer
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O0 -fsanitize=address"
        - LDFLAGS="-fsanitize=address"
      script:
        - make unittests || (cat unittests/test-suite.log && false)
    - name: unittests - GCC optimisations on level 2 and AddressSanitizer
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O2 -fsanitize=address"
        - LDFLAGS="-fsanitize=address"
      script:
        - make unittests || (cat unittests/test-suite.log && false)
    - name: unittests - GCC optimisations on level 3 and AddressSanitizer
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O3 -fsanitize=address"
        - LDFLAGS="-fsanitize=address"
      script:
        - make unittests || (cat unittests/test-suite.log && false)
    - name: systemtests - GCC without optimisations and AddressSanitizer
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O0 -fsanitize=address"
        - LDFLAGS="-fsanitize=address"
      before_script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r systemtests/requirements.txt
        - autoreconf --install
        - ./configure
      script:
        - make systemtests
    - name: systemtests - GCC optimisations on level 2 and AddressSanitizer
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O2 -fsanitize=address"
        - LDFLAGS="-fsanitize=address"
      before_script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r systemtests/requirements.txt
        - autoreconf --install
        - ./configure
      script:
        - make systemtests
    - name: systemtests - GCC optimisations on level 3 and AddressSanitizer
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O3 -fsanitize=address"
        - LDFLAGS="-fsanitize=address"
      before_script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r systemtests/requirements.txt
        - autoreconf --install
        - ./configure
      script:
        - make systemtests
    - name: check all - GCC without optimisations
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O0"
      before_script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r systemtests/requirements.txt
        - autoreconf --install
        - ./configure
      script:
        - make check || (cat unittests/test-suite.log && false)
    - name: distcheck - GCC without optimisations
      os: linux
      compiler: gcc
      env:
        - CXXFLAGS="-Wall -pedantic -Werror -O0"
      before_script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r systemtests/requirements.txt
        - autoreconf --install
        - ./configure
      script:
        - make distcheck


before_install:
- env
- sudo apt-get -qq update
- sudo apt-get install -y automake autoconf libboost1.65-all-dev python3-venv


install: true


before_script:
- autoreconf --install
- ./configure


after_success: true
