FROM docker.io/library/ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
        autoconf automake \
        g++ libboost-all-dev \
        python3 python3-venv python3-pip
RUN python3 -m venv /venv
ENV PATH=/venv/bin:$PATH
RUN pip install robotframework==4.1.2

CMD /bin/bash
